### ISSUE TITLE
Comment override doesn't seem to work

### ISSUE THREAD

**Issue by ZaLiTHkA** [electrovir/prettier-plugin-multiline-arrays#15]
I've just added this plugin to my project, and overall it's working beautifully.. with one small exception: I cannot get the comment overrides to work.

I've added `"plugins": ["./node_modules/prettier-plugin-multiline-arrays"]` to my `.prettierrc` file, making use of the internal rules with no extra customisations.

trying to add either `// prettier-multiline-arrays-set-threshold: 5` or `/* prettier-multiline-arrays-set-threshold: 5 */` to the top of my JS file changes absolutely nothing.

I've also tried setting this with `prettier-multiline-arrays-next-threshold` immediately before the 3 lines that I want to keep inline, but even that doesn't work.

---

is this a "known issue" with the current plugin code, or would you need more info to debug this?

**Comment by ZaLiTHkA** [comment]
wait wait! sorry.. I was being a dumbass. 🤦🏼 

after setting the rule override comment and then _clearing my trailing comma_, the formatting came out as I expected it to.

thank you so very much, this has just solved a very long-standing annoyance of mine with Prettier. 👍🏼

**Comment by electrovir** [comment]
Glad you got it working! Sorry for the confusion on the overrides, at this point this package _just barely_ works 😅 but that's been good enough so far...

**Comment by ZaLiTHkA** [comment]
no worries, even with this "just barely working", it's already helped alleviate a massive headache.. so a massive thank you for that! 🖖🏼
