### ISSUE TITLE
YAML compatibility

### ISSUE THREAD

**Issue by bdovaz** [electrovir/prettier-plugin-multiline-arrays#16]
@electrovir is it compatible? it appears not:

https://github.com/electrovir/prettier-plugin-multiline-arrays/blob/main/src/index.ts#L21

Can it be made compatible?

**Comment by electrovir** [comment]
I haven't tried this package with YAML. It expect it won't work, but you never know! I suspect that to make it compatible would require a new code flow just for yaml because of how specific the code is.

**Comment by bdovaz** [comment]
But then, are you going to review and implement it? My TypeScript knowledge is null, otherwise I would try to do a PR.

Thank you, for your work!

**Comment by electrovir** [comment]
At this time I have no plan to support other languages, sorry 😕
