### ISSUE TITLE
Prettier v3 compatibility

### ISSUE THREAD

**Issue by richardsimko** [electrovir/prettier-plugin-multiline-arrays#26]
Is this plugin compatible with Prettier 3.0? From my understanding there's been quite a few breaking changes to the API but I don't know if it affects the things used in the plugin.

**Comment by electrovir** [comment]
Hi @richardsimko! I haven't tried v3 yet. I'll try it out when I can (maybe this weekend?) but if anyone gets to it first, please note the results here :)

**Comment by richardsimko** [comment]
Thanks for the quick response! We have some issues but I can't validate if it's due to this plugin or all the other breaking changes in v3 :)

The first one was an easy fix, apparently v3 doesn't accept paths to plugins any more so 

```
"plugins": [
        "./node_modules/prettier-plugin-multiline-arrays"
    ],
```

needs to be changed to 

```
"plugins": [
        "./node_modules/prettier-plugin-multiline-arrays/dist/index.js"
    ],
```

or

```
"plugins": [
        "prettier-plugin-multiline-arrays"
    ],
```

both seem to at least find the plugin.

However after that I get

```
TypeError: Cannot read properties of undefined (reading 'filter')
    at Object.<anonymous> (./node_modules/prettier-plugin-multiline-arrays/dist/index.js:29:63)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
```

but I don't see an obvious reason why since the functions i'ts calling is seemingly the same in v3 as v3 although I can't say prettier plugins is an area of expertise of mine so I could be mistaken.

**Comment by electrovir** [comment]
failure from here: https://github.com/electrovir/prettier-plugin-multiline-arrays/blob/a80b3284f18553b2097fab8bcff2c8ee69647564/src/index.ts#L24

The output from `getSupportInfo()` must've changed, and I'm sure other things will break after that is fixed. I'll investigate further, probably this weekend.

**Comment by eric-coker** [comment]
`getSupportInfo()` now returns a Promise instead of an object -- so async/await will need to be used to get that info.

**Comment by electrovir** [comment]
Thanks @eric-coker, that'll be a tricky one to resolve unless I can use top level awaits. There are other issues as well with the v3 update as well, including the removal of the `concat` type (which this plugin is checking for). I'll keep this issue updated with my progress!

**Comment by electrovir** [comment]
potentially relevant: https://github.com/prettier/prettier/issues/13729#issue-1422610424

**Comment by electrovir** [comment]
I'm currently stuck on this error:

```
TypeError: Cannot read properties of undefined (reading 'type')
     at Si (node_modules/prettier/plugins/estree.mjs:28:24540)
     at Sc (node_modules/prettier/plugins/estree.mjs:28:34997)
     at Object.bc (node_modules/prettier/plugins/estree.mjs:28:35405)
     at Proxy.<anonymous> (node_modules/prettier-plugin-multiline-arrays/dist/printer/multiline-array-printer.js:15:58)
```

Which is getting thrown from this line: https://github.com/electrovir/prettier-plugin-multiline-arrays/blob/2bb919a0d2148091bb29b85bd68e33cebe6d61f6/src/printer/multiline-array-printer.ts#L21C25-L21C25

I haven't figured out what to do yet, because the inputs to `.print()` are the same in all the following situations:
- inside this plugin before v3
- inside this plugin after v3
- in the Prettier code itself with no plugins

**Comment by bdovaz** [comment]
If it helps: https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F

**Comment by AlexOstrovsky** [comment]
any update on this?

**Comment by electrovir** [comment]
Sorry, I have had no time to commit to this yet and I currently have no leads with the issues I'm running into in #27 😔

**Comment by richardsimko** [comment]
Let me know if I can help, this seems to be the only thing we use that doesn't support Prettier v3 and we really like it so we don't want to drop it :)

**Comment by electrovir** [comment]
Feel free to take a whack at #27 (branch `prettier-v3-support`)! I left some comments in the PR explaining the situation a bit.

**Comment by aotaduy** [comment]
It would be great to have this plugin in v3, will try to find some time to help with the PR.

**Comment by tthornton3-chwy** [comment]
#28 Should close this out :)

**Comment by electrovir** [comment]
Version 3.0.0 of this package has been released with support for Prettier v3! https://www.npmjs.com/package/prettier-plugin-multiline-arrays/v/3.0.0

I'm going to keep this ticket open while I test it in live use cases.

**Comment by electrovir** [comment]
The update seems to be working without issue in several large-ish codebase. I'm considering this complete! Please open new issues if you find problems with the update. Thanks to @tthornton3-chwy and @richardsimko for their contributions that made this update possible! 🥳

**Comment by nelson6e65** [comment]
Nice! I'll try it.

Thanks!

**Comment by richardsimko** [comment]
Thanks @tthornton3-chwy and @electrovir, it works great!
