### ISSUE TITLE
Not compatible with prettier-plugin-tailwindcss

### ISSUE THREAD

**Issue by bingtsingw** [electrovir/prettier-plugin-multiline-arrays#31]
This plugin seems not compatible with https://github.com/tailwindlabs/prettier-plugin-tailwindcss

**Comment by jonrouleau** [comment]
This has been fixed in `prettier-plugin-tailwindcss@0.6.6`. `prettier-plugin-multiline-arrays` should be placed in the plugins array before `prettier-plugin-tailwindcss`
