### ISSUE TITLE
Broken on prettier@3.3.0

### ISSUE THREAD

**Issue by SiNONiMiTY** [electrovir/prettier-plugin-multiline-arrays#33]
With the recent update of prettier, it broke this plugin with an error

`Error: Found "[" but: its sibling was not an indent Doc.: prettier`

This plugin might need some adjustments.

**Comment by sepek** [comment]
Should be a dup of #32, sorry I was a bit faster :grin:

**Comment by SiNONiMiTY** [comment]
funny we had the same issue, im closing this one
